import DeviceBase from "./device-base.model"

export class Model1707v3_2 extends DeviceBase {
  constructor() {
    super();
    this.energyData = new EnergyData()
  }

    getEnergyData(jsonData) {
        this.energyData.hardwareVersion.value = jsonData.B0;
        this.energyData.softwareVersion.value = jsonData.B4;
        this.energyData.switchFrequency.value = jsonData.B8;
        this.energyData.deadTime.value = jsonData.B10;
        this.energyData.errorCode.value = jsonData.B12;
        this.energyData.UVLineVoltage.value = jsonData.B14;
        this.energyData.VWLineVoltage.value = jsonData.B16;
        this.energyData.WULineVoltage.value = jsonData.B18;
        this.energyData.UPhaseVoltage.value = jsonData.B20;
        this.energyData.VPhaseVoltage.value = jsonData.B22;
        this.energyData.WPhaseVoltage.value = jsonData.B24;
        this.energyData.UPhaseCurrent.value = jsonData.B26;
        this.energyData.VPhaseCurrent.value = jsonData.B28;
        this.energyData.WPhaseCurrent.value = jsonData.B30;
        this.energyData.offGridFrequency.value = jsonData.B32;
        this.energyData.gridFrequency.value = jsonData.B34;
        this.energyData.ACLeakage.value = jsonData.B36;
        this.energyData.insideTemperature.value = jsonData.B38;
        this.energyData.PhaseATemperature.value = jsonData.B40;
        this.energyData.PhaseBTemperature.value = jsonData.B42;
        this.energyData.PhaseCTemperature.value = jsonData.B44;
        this.energyData.DCVoltage.value = jsonData.B46;
        this.energyData.DCCurrent.value = jsonData.B48;
        this.energyData.totalDCPower.value = jsonData.B50;
        this.energyData.apparentPower.value = jsonData.B52;
        this.energyData.activePower.value = jsonData.B54;
        this.energyData.reactivePower.value = jsonData.B56;
        this.energyData.PhaseUApparentPower.value = jsonData.B58;
        this.energyData.PhaseUActivePower.value = jsonData.B60;
        this.energyData.PhaseUPF.value = jsonData.B62;
        this.energyData.PhaseUCarryingCapacity.value = jsonData.B64;
        this.energyData.PhaseVApparentPower.value = jsonData.B66;
        this.energyData.PhaseVActivePower.value = jsonData.B68;
        this.energyData.PhaseVPF.value = jsonData.B70;
        this.energyData.PhaseVCarryingCapacity.value = jsonData.B72;
        this.energyData.PhaseAVoltage.value = jsonData.B74;
        this.energyData.PhaseBVoltage.value = jsonData.B76;
        this.energyData.PhaseCVoltage.value = jsonData.B78;
        this.energyData.ACPhaseACurrent.value = jsonData.B80;
        this.energyData.ACPhaseCCurrent.value = jsonData.B82;
        this.energyData.PhaseCActivePower.value = jsonData.B84;
        this.energyData.dailyCharge.value = jsonData.B88;
        this.energyData.dailyDischarge.value = jsonData.B92;
        this.energyData.ACActivePower.value = jsonData.B96;
        this.energyData.DCReactivePower.value = jsonData.B98;
        this.energyData.totalCharge.value = jsonData.B100;
        this.energyData.totalDischarge.value = jsonData.B104;
        this.energyData.ACApparentPower.value = jsonData.B108;
        this.energyData.DCVoltage.value = jsonData.B110;
        this.energyData.DCCurrent.value = jsonData.B112;
        this.energyData.DCPower.value = jsonData.B114;
        this.energyData.availablePower.value = jsonData.B116;
        this.energyData.converterCurrentSettings.value = jsonData.B118;
        this.energyData.upperBusVoltage.value = jsonData.B120;
        this.energyData.lowerBusVoltage.value = jsonData.B122;
        this.energyData.IdSettingValue.value = jsonData.B124;
        this.energyData.IqSettingValue.value = jsonData.B126;
        this.energyData.IdRealValue.value = jsonData.B128;
        this.energyData.IqRealValue.value = jsonData.B130;
        this.energyData.converterUsd.value = jsonData.B132;
        this.energyData.converterUsq.value = jsonData.B134;
        this.energyData.controlVoltageUd.value = jsonData.B136;
        this.energyData.controlVoltageUq.value = jsonData.B138;
        this.energyData.enableFlagOne.value = jsonData.B140;
        this.energyData.enableFlagTwo.value = jsonData.B142;
        this.energyData.powerFactor.value = jsonData.B144;
        this.energyData.converterControlParams.value = jsonData.B146;
        this.energyData.PvInsulationProtectionValue.value = jsonData.B160;
        this.energyData.batteryTotalVoltage.value = jsonData.B162;
        this.energyData.batteryTotalCurrent.value = jsonData.B164;
        this.energyData.batterySOC.value = jsonData.B166;
        this.energyData.batterySOH.value = jsonData.B168;
        this.energyData.chargeLimitCurrent.value = jsonData.B170;
        this.energyData.dischargeLimitCurrent.value = jsonData.B172;
        this.energyData.chargeLimitVoltage.value = jsonData.B174;
        this.energyData.dischargeLimitVoltage.value = jsonData.B176;
        this.energyData.availableElectricity.value = jsonData.B178;
    }

}
class EnergyData {
    hardwareVersion = { name: '设备硬件版本', value: '--' }
    softwareVersion = { name: '设备软件版本', value: '--' }
    switchFrequency = { name: '开关频率', value: '--' }
    deadTime = { name: '死区时间', value: '--' }
    errorCode = { name: '当前故障代码', value: '--' }
    UVLineVoltage = { name: 'UV 电网线电压(V)', value: '--' }
    VWLineVoltage = { name: 'VW 电网线电压(V)', value: '--' }
    WULineVoltage = { name: 'WU 电网线电压(V)', value: '--' }
    UPhaseVoltage = { name: 'U 相输出电压(V)', value: '--' }
    VPhaseVoltage = { name: 'V 相输出电压(V)', value: '--' }
    WPhaseVoltage = { name: 'W 相输出电压(V)', value: '--' }
    UPhaseCurrent = { name: 'U 相输出电流(A)', value: '--' }
    VPhaseCurrent = { name: 'V 相输出电流(A)', value: '--' }
    WPhaseCurrent = { name: 'W 相输出电流(A)', value: '--' }
    offGridFrequency = { name: '离网频率(Hz)', value: '--' }
    gridFrequency = { name: '电网频率(Hz)', value: '--' }
    ACLeakage = { name: '交流漏电流(A)', value: '--' }
    insideTemperature = { name: '内部温度(℃)', value: '--' }
    PhaseATemperature = { name: 'A相模块温度(℃)', value: '--' }
    PhaseBTemperature = { name: 'B相模块温度(℃)', value: '--' }
    PhaseCTemperature = { name: 'C相模块温度(℃)', value: '--' }
    DCVoltage = { name: '直流电压(V)', value: '--' }
    DCCurrent = { name: '直流电流(A)', value: '--' }
    totalDCPower = { name: '总直流功率(kW)', value: '--' }
    apparentPower = { name: '输出视在功率(kVA)', value: '--' }
    activePower = { name: '输出有功功率(kW)', value: '--' }
    reactivePower = { name: '输出无功功率(kW)', value: '--' }
    PhaseUApparentPower = { name: 'U 相输出视在功率(kVA)', value: '--' }
    PhaseUActivePower = { name: 'U 相输出有功功率(kW)', value: '--' }
    PhaseUPF = { name: 'U 相 PF 值', value: '--' }
    PhaseUCarryingCapacity = { name: 'U 相负载量(%)', value: '--' }
    PhaseVApparentPower = { name: 'V 相输出视在功率(kVA)', value: '--' }
    PhaseVActivePower = { name: 'V 相输出有功功率(kW)', value: '--' }
    PhaseVPF = { name: 'V 相 PF 值', value: '--' }
    PhaseVCarryingCapacity = { name: 'V 相负载量(%)', value: '--' }
    PhaseAVoltage = { name: 'A相电压(V)', value: '--' }
    PhaseBVoltage = { name: 'B相电压(V)', value: '--' }
    PhaseCVoltage = { name: 'C相电压(V)', value: '--' }
    ACPhaseACurrent = { name: '交流A相电流(A)', value: '--' }
    ACPhaseCCurrent = { name: '交流C相电流(A)', value: '--' }
    PhaseCActivePower = { name: 'C相有功功率(kW)', value: '--' }
    dailyCharge = { name: '当日充电量(kWh)', value: '--' }
    dailyDischarge = { name: '当日放电量(kWh)', value: '--' }
    ACActivePower = { name: '交流有功功率(kW)', value: '--' }
    DCReactivePower = { name: '交流无功功率(kW)', value: '--' }
    totalCharge = { name: '总充电量(kWh)', value: '--' }
    totalDischarge = { name: '总放电量(kWh)', value: '--' }
    ACApparentPower = { name: '交流视在功率(kVA)', value: '--' }
    DCVoltage = { name: '直流电压(V)', value: '--' }
    DCCurrent = { name: '直流电流(V)', value: '--' }
    DCPower = { name: '直流功率(V)', value: '--' }
    availablePower = { name: '可用功率(kVA)', value: '--' }
    converterCurrentSettings = { name: '变流器当前设置参数', value: '--' }
    upperBusVoltage = { name: '上母线电压(V)', value: '--' }
    lowerBusVoltage = { name: '下母线电压(V)', value: '--' }
    IdSettingValue = { name: 'Id给定值(A)', value: '--' }
    IqSettingValue = { name: 'Iq给定值(A)', value: '--' }
    IdRealValue = { name: 'Id实际值(A)', value: '--' }
    IqRealValue = { name: 'Iq实际值(A)', value: '--' }
    converterUsd = { name: '变流器侧Usd(V)', value: '--' }
    converterUsq = { name: '变流器侧Usq(V)', value: '--' }
    controlVoltageUd = { name: '控制电压Ud(V)', value: '--' }
    controlVoltageUq = { name: '控制电压Uq(V)', value: '--' }
    enableFlagOne = { name: '功能使能标志位1', value: '--' }
    enableFlagTwo = { name: '功能使能标志位2', value: '--' }
    powerFactor = { name: '功率因数', value: '--' }
    converterControlParams = { name: '变流器控制参数', value: '--' }
    PvInsulationProtectionValue = { name: '光伏绝缘保护值(kΩ)', value: '--' }
    batteryTotalVoltage = { name: '电池组总电压(V)', value: '--' }
    batteryTotalCurrent = { name: '电池组总电流(A)', value: '--' }
    batterySOC = { name: '电池组 SOC(%)', value: '--' }
    batterySOH = { name: '电池组 SOH(%)', value: '--' }
    chargeLimitCurrent = { name: '充电限制电流(A)', value: '--' }
    dischargeLimitCurrent = { name: '放电限制电流(A)', value: '--' }
    chargeLimitVoltage = { name: '充电限制电压(V)', value: '--' }
    dischargeLimitVoltage = { name: '放电限制电压(V)', value: '--' }
    availableElectricity = { name: '充电可用电量(kWh)', value: '--' }
}
