
import DeviceBase from "./device-base.model"

class Model170A extends DeviceBase {

    energyData;
    stateData;

    constructor() {
        super();
        this.energyData = new EnergyData();
        this.stateData = new StateData();
        // var energyData = ref(EnergyData)
    }

    getEnergyData(jsonData, jsonData2, barCode) {
        // this.energyData.power = jsonData.B0
        this.energyData.frameTime = jsonData2.dateTime
        this.energyData.group_voltage = jsonData.B0.toFixed(2) // '组端电压',
        this.energyData.group_current = jsonData.B2.toFixed(2) // '组电流',
        this.energyData.group_soc = jsonData.B4.toFixed(2) //'组soc',
        this.energyData.group_soh = jsonData.B6.toFixed(2) + '%' // '组soh',
        this.energyData.environment_temperature = (jsonData.B8).toFixed(2) + '℃' // '环境温度',
        this.energyData.group_positive_insulation_resistance = jsonData.B10.toFixed(2) //  '组正极绝缘电阻',
        this.energyData.group_negative_insulation_resistance = jsonData.B12.toFixed(2) //  '组负极绝缘电阻',
        this.energyData.group_charge_capacity = jsonData.B14.toFixed(2) // '组可充电量',
        this.energyData.group_discharge_capacity = jsonData.B16.toFixed(2) // '组可放电量',
        this.energyData.group_single_charge_capacity = jsonData.B18.toFixed(2) // '组单次充电电量',
        this.energyData.group_single_discharge_capacity = jsonData.B20.toFixed(2) // '组单次放电电量',
        this.energyData.group_total_charge_capacity = jsonData.B22.toFixed(2) // '组累计充电电量',
        this.energyData.group_total_discharge_capacity = jsonData.B24.toFixed(2) // '组累计放电电量',
        this.energyData.group_single_voltage_range_of_pressure = jsonData.B26.toFixed(2) // '组单体电压压差极差值',
        this.energyData.single_avg_voltage = jsonData.B28.toFixed(2) // '单体电压平均值',
        this.energyData.single_max_voltage = jsonData.B30.toFixed(2) // '单电电压最大值',
        this.energyData.single_min_voltage = jsonData.B32.toFixed(2) // '单电电压最小值',
        this.energyData.group_single_temperature_range_of_pressure = jsonData.B34.toFixed(2) // '组单体温度温差极差值',
        this.energyData.single_avg_temperature = jsonData.B36.toFixed(2) // '单体温度平均值',
        this.energyData.single_max_temperature = jsonData.B38.toFixed(2) // '单电温度最大值',
        this.energyData.single_min_temperature = jsonData.B40.toFixed(2) // '单电温度最小值',
        this.energyData.single_avg_internal_resistance = jsonData.B42.toFixed(2) //  '单体平均内阻',
        this.energyData.single_max_internal_resistance = jsonData.B44.toFixed(2) //  '单体内阻最大值',
        this.energyData.single_min_internal_resistance = jsonData.B46.toFixed(2) //  '单体内阻最小值',
        this.energyData.single_avg_soc = jsonData.B48.toFixed(2) // '单体SOC平均值',
        this.energyData.single_max_soc = jsonData.B50.toFixed(2) // '单体SOC最大值',
        this.energyData.single_min_soc = jsonData.B52.toFixed(2) // '单体SOC最小值',
        this.energyData.single_avg_soh = jsonData.B54.toFixed(2) //  '单体SOH平均值',
        this.energyData.single_max_soh = jsonData.B56.toFixed(2) //  '单体SOH最大值',
        this.energyData.single_min_soh = jsonData.B58.toFixed(2) //  '单体SOH最小值',
        this.energyData.group_current_maximum_allowable_charge_power = jsonData.B60.toFixed(2) // '组当前允许最大充电功率',
        this.energyData.group_current_maximum_allowable_discharge_power = jsonData.B62.toFixed(2) // '组当前允许最大放电功率',
        this.energyData.group_current_maximum_allowable_charge_current = jsonData.B64.toFixed(2) // '组当前允许最大充电电流',
        this.energyData.group_current_maximum_allowable_discharge_current = jsonData.B66.toFixed(2) // '组当前允许最大放电电流',
        this.energyData.low_side_voltage = jsonData.B68.toFixed(2) //  '低压侧电压值',
        this.energyData.low_side_current = jsonData.B70.toFixed(2) // '低压侧电流值',
        this.energyData.heat_sink_temperature = jsonData.B72.toFixed(2) + '℃' // '散热器温度值',
        this.energyData.high_side_voltage = jsonData.B74.toFixed(2) //  '高压侧电压值',
        this.energyData.high_side_current = jsonData.B76.toFixed(2) // '高压侧电流值',
        this.energyData.dc_bus_high_side_voltage = jsonData.B78.toFixed(2) + "V" //  '高压侧端口电压值（直流母线电压）',
        this.energyData.battery_low_side_voltage = jsonData.B80.toFixed(2) + "V" //  '低压侧端口电压值（电池电压）',

    }

    setDCDCWorkingState(key) {
        switch (key) {
            case '0000':
                return '待机'
            case '5555':
                return '充电'
            case '6666':
                return '恒流放电'
            case '7777':
                return '恒压放电'
            default:
                return key;
        }
    }

    setBatteryChargeState(key) {
        switch (key) {
            case 1:
                return '开路'
            case 2:
                return '待机'
            case 3:
                return '充电'
            case 4:
                return '放电'
            default:
                return key;
            // break;
        }
    }

    getStatusData(jsonData) {
        this.stateData.frameTime = jsonData.dateTime
        this.stateData.group_battery_running_status = jsonData.data.B0      //  '电池组运行状态',
        this.stateData.group_battery_charge_status = this.setBatteryChargeState(jsonData.data.B2)    //  '电池组充放电状态',
        this.stateData.number_of_battery_jurisdiction = jsonData.data.B4    //  '电池组管辖电池节数',
        this.stateData.number_of_battery_jurisdiction_temperature = jsonData.data.B6    //  '电池组管辖温度节数',
        this.stateData.number_of_battery_jurisdiction_pack = jsonData.data.B8    //  '电池组管辖PACK数',
        this.stateData.number_of_battery_charge = jsonData.data.B10    //  '电池组充电次数',
        this.stateData.number_of_battery_discharge = jsonData.data.B12    //  '电池组放电次数',
        this.stateData.single_max_voltage = jsonData.data.B14    //  '单体电压最大节号',
        this.stateData.single_min_voltage = jsonData.data.B16    //  '单体电压最小节号',
        this.stateData.single_max_temperature = jsonData.data.B18    //  '单体温度最大节号',
        this.stateData.single_min_temperature = jsonData.data.B20    //  '单体温度最小节号',
        this.stateData.single_max_internal_resistance = jsonData.data.B22    //  '单体内阻最大节号',
        this.stateData.single_min_internal_resistance = jsonData.data.B24    //  '单体内阻最小节号',
        this.stateData.single_max_soc = jsonData.data.B26    //  '单体SOC最大节号',
        this.stateData.single_min_soc = jsonData.data.B28    //  '单体SOC最小节号',
        this.stateData.single_max_soh = jsonData.data.B30    //  '单体SOH最大节号',
        this.stateData.single_min_soh = jsonData.data.B32    //  '单体SOH最小节号',
        this.stateData.on_of_input_DI1 = jsonData.data.B34    //  '开关量输入-DI1',
        this.stateData.on_of_input_DI2 = jsonData.data.B36    //  '开关量输入-DI2',
        this.stateData.control_type = jsonData.data.B38 == '1111' ? true : false //  '控制类型',
        this.stateData.DCDC_on_off = jsonData.data.B40    //  'DCDC开关机',
        this.stateData.DCDC_working_status = this.setDCDCWorkingState(jsonData.data.B42)    //  'DCDC工作状态',
        this.stateData.DCDC_failure_code = jsonData.data.B44    //  'DCDC故障码',
        this.stateData.DCDC_status_code = jsonData.data.B46    //  'DCDC状态码',
        this.stateData.group_voltage_uper_limit_early_alarm = jsonData.data.B48b0    //  '组端电压上限预警',
        this.stateData.group_voltage_lower_limit_early_alarm = jsonData.data.B48b1    //  '组端电压下限预警',
        this.stateData.charge_current_uper_limit_early_alarm = jsonData.data.B48b2    //  '充电电流上限预警',
        this.stateData.discharge_current_uper_limit_early_alarm = jsonData.data.B48b3    //  '放电电流上限预警',
        this.stateData.single_voltage_uper_limit_early_alarm = jsonData.data.B48b4    //  '单体电压上限预警',
        this.stateData.single_voltage_lower_limit_early_alarm = jsonData.data.B48b5   //  '单体电压下限预警',
        this.stateData.charge_temperature_uper_limit_early_alarm = jsonData.data.B48b6    //  '充电温度上限预警',
        this.stateData.charge_temperature_lower_limit_early_alarm = jsonData.data.B48b7    //  '充电温度下限预警',
        this.stateData.discharge_temperature_uper_limit_early_alarm = jsonData.data.B49b0    //  '放电温度上限预警',
        this.stateData.discharge_temperature_lower_limit_early_alarm = jsonData.data.B49b1    //  '放电温度下限预警',
        this.stateData.single_temperature_uper_limit_early_alarm = jsonData.data.B49b2    //  '单体温度上限预警',
        this.stateData.single_temperature_lower_limit_early_alarm = jsonData.data.B49b3    //  '单体温度下限预警',
        this.stateData.environment_temperature_uper_limit_early_alarm = jsonData.data.B49b4    //  '环境温度上限预警',
        this.stateData.environment_temperature_lower_limit_early_alarm = jsonData.data.B49b5   //  '环境温度下限预警',
        this.stateData.power_line_temperature_uper_limit_early_alarm = jsonData.data.B49b6    //  '动力线温度上限预警',
        this.stateData.group_soc_uper_limit_early_alarm = jsonData.data.B49b7    //  '组SOC上限预警',
        this.stateData.group_soc_lower_limit_early_alarm = jsonData.data.B50b0    //  '组SOC下限预警',
        this.stateData.positive_insulation_resistance_lower_limit_early_alarm = jsonData.data.B50b1     //  '正极绝缘电阻下限预警',
        this.stateData.negative_insulation_resistance_lower_limit_early_alarm = jsonData.data.B50b2      //  '负极绝缘电阻下限预警',
        this.stateData.case_voltage_uper_limit_early_alarm = jsonData.data.B50b3     //  '箱压差上限预警',
        this.stateData.case_temperature_uper_limit_early_alarm = jsonData.data.B50b4     //  '箱温差上限预警',
        this.stateData.group_voltage_uper_limit_alarm = jsonData.data.B50b5     //  '组端电压上限告警',
        this.stateData.group_voltage_lower_limit_alarm = jsonData.data.B50b6     //  '组端电压下限告警',
        this.stateData.charge_current_uper_limit_alarm = jsonData.data.B50b7   //  '充电电流上限告警',
        this.stateData.discharge_current_uper_limit_alarm = jsonData.data.B51b0    //  '放电电流上限告警',
        this.stateData.single_voltage_uper_limit_alarm = jsonData.data.B51b1    //  '单体电压上限告警',
        this.stateData.single_voltage_lower_limit_alarm = jsonData.data.B51b2    //  '单体电压下限告警',
        this.stateData.charge_temperature_uper_limit_alarm = jsonData.data.B51b3    //  '充电温度上限告警',
        this.stateData.charge_temperature_lower_limit_alarm = jsonData.data.B51b4    //  '充电温度下限告警',
        this.stateData.discharge_temperature_uper_limit_alarm = jsonData.data.B51b5    //  '放电温度上限告警',
        this.stateData.discharge_temperature_lower_limit_alarm = jsonData.data.B51b6    //  '放电温度下限告警',
        this.stateData.single_temperature_uper_limit_alarm = jsonData.data.B51b7    //  '单体温度上限告警',
        this.stateData.single_temperature_lower_limit_alarm = jsonData.data.B52b0    //  '单体温度下限告警',
        this.stateData.environment_temperature_uper_limit_alarm = jsonData.data.B52b1    //  '环境温度上限告警',
        this.stateData.environment_temperature_lower_limit_alarm = jsonData.data.B52b2    //  '环境温度下限告警',
        this.stateData.power_line_temperature_uper_limit_alarm = jsonData.data.B52b3   //  '动力线温度上限告警',
        this.stateData.group_soc_uper_limit_alarm = jsonData.data.B52b4    //  '组SOC上限告警',
        this.stateData.group_soc_lower_limit_alarm = jsonData.data.B52b5   //  '组SOC下限告警',
        this.stateData.positive_insulation_resistance_lower_limit_alarm = jsonData.data.B52b6    //  '正极绝缘电阻下限告警',
        this.stateData.negative_insulation_resistance_lower_limit_alarm = jsonData.data.B52b7    //  '负极绝缘电阻下限告警',
        this.stateData.case_voltage_uper_limit_alarm = jsonData.data.B53b0     //  '箱压差上限告警',
        this.stateData.case_temperature_uper_limit_alarm = jsonData.data.B53b1     //  '箱温差上限告警',
        this.stateData.group_voltage_uper_limit_protect = jsonData.data.B53b2    //  '组端电压上限保护',
        this.stateData.group_voltage_lower_limit_protect = jsonData.data.B53b3     //  '组端电压下限保护',
        this.stateData.charge_current_uper_limit_protect = jsonData.data.B53b4    //  '充电电流上限保护',
        this.stateData.discharge_current_uper_limit_protect = jsonData.data.B53b5     //  '放电电流上限保护',
        this.stateData.single_voltage_uper_limit_protect = jsonData.data.B53b6     //  '单体电压上限保护',
        this.stateData.single_voltage_lower_limit_protect = jsonData.data.B53b7    //  '单体电压下限保护',
        this.stateData.charge_temperature_uper_limit_protect = jsonData.data.B54b0    //  '充电温度上限保护',
        this.stateData.charge_temperature_lower_limit_protect = jsonData.data.B54b1    //  '充电温度下限保护',
        this.stateData.discharge_temperature_uper_limit_protect = jsonData.data.B54b2    //  '放电温度上限保护',
        this.stateData.discharge_temperature_lower_limit_protect = jsonData.data.B54b3    //  '放电温度下限保护',
        this.stateData.single_temperature_uper_limit_protect = jsonData.data.B54b4    //  '单体温度上限保护',
        this.stateData.single_temperature_lower_limit_protect = jsonData.data.B54b5   //  '单体温度下限保护',
        this.stateData.environment_temperature_uper_limit_protect = jsonData.data.B54b6    //  '环境温度上限保护',
        this.stateData.environment_temperature_lower_limit_protect = jsonData.data.B54b7    //  '环境温度下限保护',
        this.stateData.power_line_temperature_uper_limit_protect = jsonData.data.B55b0    //  '动力线温度上限保护',
        this.stateData.group_soc_uper_limit_protect = jsonData.data.B55b1    //  '组SOC上限保护',
        this.stateData.group_soc_lower_limit_protect = jsonData.data.B55b2    //  '组SOC下限保护',
        this.stateData.positive_insulation_resistance_lower_limit_protect = jsonData.data.B55b3    //  '正极绝缘电阻下限保护',
        this.stateData.negative_insulation_resistance_lower_limit_protect = jsonData.data.B55b4    //  '负极绝缘电阻下限保护',
        this.stateData.case_voltage_uper_limit_protect = jsonData.data.B55b5    //  '箱压差上限保护',
        this.stateData.case_temperature_uper_limit_protect = jsonData.data.B55b6    //  '箱温差上限保护',
        this.stateData.battery_temperature_rise_too_fast = jsonData.data.B55b7     //  '电池温度温升过快',
        this.stateData.power_line_rise_too_fast = jsonData.data.B56b00     //  '动力线温度温升过快',
        this.stateData.bmu_fault = jsonData.data.B56b1     //  'BMU通讯故障',
        this.stateData.bcmu_fault = jsonData.data.B56b2     //  'BCMU通讯故障',
        this.stateData.single_valtage_collect_line_fault = jsonData.data.B56b3     //  '单体电压采集线故障',
        this.stateData.total_voltage_collect_line_fault = jsonData.data.B56b4     //  '总压采集线故障',
        this.stateData.current_collect_line_fault = jsonData.data.B56b5     //  '电流采集线故障',
        this.stateData.temperature_collect_broken_line = jsonData.data.B56b6     //  '温度采集断线',
        this.stateData.temperature_collect_short_circuit = jsonData.data.B56b7    //  '温度采集短路',
        this.stateData.bms_fault = jsonData.data.B57b0    //  'BMS设备故障',
        this.stateData.single_voltage_ineffectiveness = jsonData.data.B57b1    //  '单体电压无效',
        this.stateData.single_temperature_ineffectiveness = jsonData.data.B57b2    //  '单体温度无效',
        this.stateData.group_voltage_ineffectiveness = jsonData.data.B57b3    //  '组端电压无效',
        this.stateData.group_current_abnormity = jsonData.data.B57b4    //  '组电流异常',
        this.stateData.fire_alarm = jsonData.data.B57b5    //  '消防报警',
        this.stateData.water_alarm = jsonData.data.B57b6    //  '水浸报警',
        this.stateData.cache_alarm = jsonData.data.B57b7   //  '缓存告警待获取',
    }

}
class EnergyData {
    frameTime;
    group_voltage = "--"// '组端电压',
    group_currente = "--"// '组电流',
    group_soc = "0"//'组soc',
    group_soh = "--"// '组soh',
    environment_temperature// '环境温度',
    group_positive_insulation_resistance //  '组正极绝缘电阻',
    group_negative_insulation_resistance //  '组负极绝缘电阻',
    group_charge_capacity// '组可充电量',
    group_discharge_capacity// '组可放电量',
    group_single_charge_capacity// '组单次充电电量',
    group_single_discharge_capacity// '组单次放电电量',
    group_total_charge_capacity// '组累计充电电量',
    group_total_discharge_capacity// '组累计放电电量',
    group_single_voltage_range_of_pressure// '组单体电压压差极差值',
    single_avg_voltage// '单体电压平均值',
    single_max_voltage// '单电电压最大值',
    single_min_voltage// '单电电压最小值',
    group_single_temperature_range_of_pressure// '组单体温度温差极差值',
    single_avg_temperature// '单体温度平均值',
    single_max_temperature// '单电温度最大值',
    single_min_temperature// '单电温度最小值',
    single_avg_internal_resistance //  '单体平均内阻',
    single_max_internal_resistance //  '单体内阻最大值',
    single_min_internal_resistance //  '单体内阻最小值',
    single_avg_soc// '单体SOC平均值',
    single_max_soc// '单体SOC最大值',
    single_min_soc// '单体SOC最小值',
    single_avg_soh //  '单体SOH平均值',
    single_max_soh //  '单体SOH最大值',
    single_min_soh //  '单体SOH最小值',
    group_current_maximum_allowable_charge_power// '组当前允许最大充电功率',
    group_current_maximum_allowable_discharge_power// '组当前允许最大放电功率',
    group_current_maximum_allowable_charge_current// '组当前允许最大充电电流',
    group_current_maximum_allowable_discharge_current// '组当前允许最大放电电流',
    low_side_voltage //  '低压侧电压值',
    low_side_current// '低压侧电流值',
    heat_sink_temperature = "-- ℃" // '散热器温度值',
    high_side_voltage //  '高压侧电压值',
    high_side_current// '高压侧电流值',
    dc_bus_high_side_voltage = "-- V" //  '高压侧端口电压值（直流母线电压）',
    battery_low_side_voltage = "-- V" //  '低压侧端口电压值（电池电压）',

}

class StateData {
    frameTime;
    group_battery_running_status //  '电池组运行状态',
    group_battery_charge_status //  '电池组充放电状态',
    number_of_battery_jurisdiction //  '电池组管辖电池节数',
    number_of_battery_jurisdiction_temperature //  '电池组管辖温度节数',
    number_of_battery_jurisdiction_pack //  '电池组管辖PACK数',
    number_of_battery_charge //  '电池组充电次数',
    number_of_battery_discharge //  '电池组放电次数',
    single_max_voltage //  '单体电压最大节号',
    single_min_voltage //  '单体电压最小节号',
    single_max_temperature //  '单体温度最大节号',
    single_min_temperature //  '单体温度最小节号',
    single_max_internal_resistance //  '单体内阻最大节号',
    single_min_internal_resistance //  '单体内阻最小节号',
    single_max_soc //  '单体SOC最大节号',
    single_min_soc //  '单体SOC最小节号',
    single_max_soh //  '单体SOH最大节号',
    single_min_soh //  '单体SOH最小节号',
    on_of_input_DI1 //  '开关量输入-DI1',
    on_of_input_DI2 //  '开关量输入-DI2',
    control_type //  '控制类型',
    DCDC_on_off //  'DCDC开关机',
    DCDC_working_status = "--"//  'DCDC工作状态',
    DCDC_failure_code //  'DCDC故障码',
    DCDC_status_code //  'DCDC状态码',
    group_voltage_uper_limit_early_alarm //  '组端电压上限预警',
    group_voltage_lower_limit_early_alarm //  '组端电压下限预警',
    charge_current_uper_limit_early_alarm //  '充电电流上限预警',
    discharge_current_uper_limit_early_alarm //  '放电电流上限预警',
    single_voltage_uper_limit_early_alarm //  '单体电压上限预警',
    single_voltage_lower_limit_early_alarm //  '单体电压下限预警',
    charge_temperature_uper_limit_early_alarm //  '充电温度上限预警',
    charge_temperature_lower_limit_early_alarm //  '充电温度下限预警',
    discharge_temperature_uper_limit_early_alarm //  '放电温度上限预警',
    discharge_temperature_lower_limit_early_alarm //  '放电温度下限预警',
    single_temperature_uper_limit_early_alarm //  '单体温度上限预警',
    single_temperature_lower_limit_early_alarm //  '单体温度下限预警',
    environment_temperature_uper_limit_early_alarm //  '环境温度上限预警',
    environment_temperature_lower_limit_early_alarm //  '环境温度下限预警',
    power_line_temperature_uper_limit_early_alarm //  '动力线温度上限预警',
    group_soc_uper_limit_early_alarm //  '组SOC上限预警',
    group_soc_lower_limit_early_alarm //  '组SOC下限预警',
    positive_insulation_resistance_lower_limit_early_alarm //  '正极绝缘电阻下限预警',
    negative_insulation_resistance_lower_limit_early_alarm //  '负极绝缘电阻下限预警',
    case_voltage_uper_limit_early_alarm //  '箱压差上限预警',
    case_temperature_uper_limit_early_alarm //  '箱温差上限预警',
    group_voltage_uper_limit_alarm //  '组端电压上限告警',
    group_voltage_lower_limit_alarm //  '组端电压下限告警',
    charge_current_uper_limit_alarm //  '充电电流上限告警',
    discharge_current_uper_limit_alarm //  '放电电流上限告警',
    single_voltage_uper_limit_alarm //  '单体电压上限告警',
    single_voltage_lower_limit_alarm //  '单体电压下限告警',
    charge_temperature_uper_limit_alarm //  '充电温度上限告警',
    charge_temperature_lower_limit_alarm //  '充电温度下限告警',
    discharge_temperature_uper_limit_alarm //  '放电温度上限告警',
    discharge_temperature_lower_limit_alarm //  '放电温度下限告警',
    single_temperature_uper_limit_alarm //  '单体温度上限告警',
    single_temperature_lower_limit_alarm //  '单体温度下限告警',
    environment_temperature_uper_limit_alarm //  '环境温度上限告警',
    environment_temperature_lower_limit_alarm //  '环境温度下限告警',
    power_line_temperature_uper_limit_alarm //  '动力线温度上限告警',
    group_soc_uper_limit_alarm //  '组SOC上限告警',
    group_soc_lower_limit_alarm //  '组SOC下限告警',
    positive_insulation_resistance_lower_limit_alarm //  '正极绝缘电阻下限告警',
    negative_insulation_resistance_lower_limit_alarm //  '负极绝缘电阻下限告警',
    case_voltage_uper_limit_alarm //  '箱压差上限告警',
    case_temperature_uper_limit_alarm //  '箱温差上限告警',
    group_voltage_uper_limit_protect //  '组端电压上限保护',
    group_voltage_lower_limit_protect //  '组端电压下限保护',
    charge_current_uper_limit_protect //  '充电电流上限保护',
    discharge_current_uper_limit_protect //  '放电电流上限保护',
    single_voltage_uper_limit_protect //  '单体电压上限保护',
    single_voltage_lower_limit_protect //  '单体电压下限保护',
    charge_temperature_uper_limit_protect //  '充电温度上限保护',
    charge_temperature_lower_limit_protect //  '充电温度下限保护',
    discharge_temperature_uper_limit_protect //  '放电温度上限保护',
    discharge_temperature_lower_limit_protect //  '放电温度下限保护',
    single_temperature_uper_limit_protect //  '单体温度上限保护',
    single_temperature_lower_limit_protect //  '单体温度下限保护',
    environment_temperature_uper_limit_protect //  '环境温度上限保护',
    environment_temperature_lower_limit_protect //  '环境温度下限保护',
    power_line_temperature_uper_limit_protect //  '动力线温度上限保护',
    group_soc_uper_limit_protect //  '组SOC上限保护',
    group_soc_lower_limit_protect //  '组SOC下限保护',
    positive_insulation_resistance_lower_limit_protect //  '正极绝缘电阻下限保护',
    negative_insulation_resistance_lower_limit_protect //  '负极绝缘电阻下限保护',
    case_voltage_uper_limit_protect //  '箱压差上限保护',
    case_temperature_uper_limit_protect //  '箱温差上限保护',
    battery_temperature_rise_too_fast //  '电池温度温升过快',
    power_line_rise_too_fast //  '动力线温度温升过快',
    bmu_fault //  'BMU通讯故障',
    bcmu_fault //  'BCMU通讯故障',
    single_valtage_collect_line_fault //  '单体电压采集线故障',
    total_voltage_collect_line_fault //  '总压采集线故障',
    current_collect_line_fault //  '电流采集线故障',
    temperature_collect_broken_line //  '温度采集断线',
    temperature_collect_short_circuit //  '温度采集短路',
    bms_fault //  'BMS设备故障',
    single_voltage_ineffectiveness //  '单体电压无效',
    single_temperature_ineffectiveness //  '单体温度无效',
    group_voltage_ineffectiveness //  '组端电压无效',
    group_current_abnormity //  '组电流异常',
    fire_alarm //  '消防报警',
    water_alarm //  '水浸报警',
    cache_alarm //  '缓存告警待获取',
}

export { Model170A };

